package org.productsstore.products.services;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtParser;
import io.jsonwebtoken.Jwts;
import org.antlr.v4.runtime.misc.Pair;


import org.productsstore.products.Dtos.EmailDto;
import org.productsstore.products.Exceptions.AccountSuspendedException;
import org.productsstore.products.Exceptions.PasswordMismatchException;
import org.productsstore.products.Exceptions.UserAlreadySignedException;
import org.productsstore.products.Exceptions.UserNotRegisteredException;
import org.productsstore.products.clients.KafkaClient;
import org.productsstore.products.models.Session;
import org.productsstore.products.models.State;
import org.productsstore.products.models.User;
import org.productsstore.products.repositories.SessionRepository;
import org.productsstore.products.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Optional;
import java.util.Map;

@Service
public class AuthService {

    @Autowired
    private UserRepository userRepo;

    @Autowired
    private SessionRepository sessionRepo;

    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;

    @Autowired
    private SecretKey secretKey;

    @Autowired
    private KafkaClient kafkaClient;

    @Autowired
    private ObjectMapper objectMapper;

    public User signup(String name, String email, String password) {
        Optional<User> userOptional = userRepo.findByEmailEquals(email);
        if(userOptional.isPresent()) {
            throw new UserAlreadySignedException("Please try login directly !!");
        }

        User user = new User();
        user.setName(name);
        user.setEmail(email);
        user.setPassword(bCryptPasswordEncoder.encode(password));

        try {
            EmailDto emailDto = new EmailDto();
            emailDto.setTo(email);
            emailDto.setFrom("support@koncert.com");
            emailDto.setSubject("Welcome to Koncert");
            emailDto.setBody("Hope you will have good experience");
            kafkaClient.sendMessage("signup", objectMapper.writeValueAsString(emailDto));
        }catch (JsonProcessingException exception) {
            throw new RuntimeException("something went wrong");
        }

        return userRepo.save(user);
    }


    public Pair<User,String> login(String email, String password) {
        Optional<User> userOptional = userRepo.findByEmailEquals(email);
        if(userOptional.isEmpty()) {
            throw new UserNotRegisteredException("Please try signup first");
        }

        if(!userOptional.get().getState().equals(State.ACTIVE)) {
            throw new AccountSuspendedException("Account is temporarily suspended, Please try after some days");
        }

        String storedPassword = userOptional.get().getPassword();
        if(!bCryptPasswordEncoder.matches(password,storedPassword))   {
            throw new PasswordMismatchException("Please type correct password");
        }

        Map<String,Object> claims = new HashMap<>();
        claims.put("userId",userOptional.get().getId());
        Long nowInMillis = System.currentTimeMillis();
        claims.put("iat",nowInMillis);
        claims.put("exp",nowInMillis+100000);
        claims.put("iss","authservice##");


        String token = Jwts.builder().claims(claims).signWith(secretKey).compact();

        Session session = new Session();
        session.setUser(userOptional.get());
        session.setToken(token);
        session.setState(State.ACTIVE);
        sessionRepo.save(session);


        Pair<User,String> response = new Pair<>(userOptional.get(),token);

        return response;
    }

    //Validate if token is being generated by us
    //Check of Expiry of Token
    public Boolean validateToken(String token,Long userId) {
        Optional<Session> optionalSession = sessionRepo.findByTokenAndUser_Id(token,userId);

        if(optionalSession.isEmpty()) {
            System.out.println("Passed Token is not valid");
            return false;
        }

        JwtParser jwtParser = Jwts.parser().verifyWith(secretKey).build();
        Claims claims = jwtParser.parseSignedClaims(token).getPayload();


        Long expiryTime = (Long)claims.get("exp");

        System.out.println("expiry = "+expiryTime);
        System.out.println("current ="+System.currentTimeMillis());
        if(expiryTime < System.currentTimeMillis()) {
            System.out.println("Token has expired");
            return false;
        }

        return true;
    }
}
